print("I awoke on impact", '\n'
"Under surveillance from the camera eye", '\n'
"Searching high and low", '\n'
"The criminal mind found at the scene of the crime", '\n'
"Handcuffed and blind, I didn't do it", '\n'
"She said she loved me", '\n'
"I guess I never knew", '\n'
"But do we ever, ever really know?", '\n'
"She said she'd meet me on the other side", '\n'
"But I knew right then, I'd never find her",'\n'
"I don't believe in love", '\n'
"I never have, I never will", '\n'
"I don't believe in love", '\n'
"It's never worth the pain that you feel", '\n'
"No more nightmares, I've seen them all", '\n'
"From the day I was born", '\n'
"They've haunted my every move", '\n'
"Every open hand's there to push and shove", '\n'
"No time for love it doesn't matter", '\n'
"She made a difference", '\n'
"I guess she had a way", '\n'
"Of making every night seem bright as day", '\n'
"Now I walk in shadows, never see the light", '\n'
"She must have lied 'cause she never said goodbye", '\n'
"I don't believe in love", '\n'
"I never have, I never will", '\n'
"I don't believe in love", '\n'
"I'll just pretend she never was real", '\n'
"I don't believe in love", '\n'
"I need to forget her face, I see it still", '\n'
"I don't believe in love", '\n'
"It's never worth the pain that you feel", '\n'
"No chance for contact", '\n'
"There's no raison d'etre", '\n'
"My only hope is one day I'll forget", '\n'
"The pain of knowing what can never be", '\n'
"With or without love it's all the same to me", '\n'
"I don't believe in love", '\n'
"I never have, I never will", '\n'
"I don't believe in love", '\n'
"I'll just pretend she never was real", '\n'
"I don't believe in love", '\n'
"I never have, I never will", '\n'
"I don't believe in love", '\n'
"It's never worth the pain that you feel, feel", '\n'
"The pain that you feel, feel", '\n')
