print("                  +                   ",'\n'
      "                 xxx                  ",'\n'
      "                xxoxx                 ",'\n'
      "               oxxxxcx                ",'\n'
      "              xxjxxjxxx               ",'\n'
      "             xxxxxxxxxxx              ",'\n'
      "                 ##                   ",'\n'
      "                 ##                   ",'\n'
      "                ####                  ")
